version: '3.6'
services:

  apache:
    image: php:7.2-apache

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
