version: '3.6'
services:

  apache:
    build: .
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "./mariadb/:/var/lib/mysql"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
